/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.jcolibri.utils.components;

import br.edu.jcolibri.constants.Attribute;
import br.edu.jcolibri.utils.ComponentUtils;
import br.edu.jcolibri.utils.Session;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Lori Machado Filho
 */
public class JAttributes extends javax.swing.JDialog {

    
     private ArrayList<String> list = null;
     private boolean ok = false;
    
   
    /**
     * Creates new form JAttributeListener
     * @param parent
     * @param modal
     * @param attribute
     */
    public JAttributes(java.awt.Frame parent, boolean modal, Attribute attribute) {
        super(parent, modal);
        init(attribute);
    }
    
    private void init(Attribute attribute){
         if(attribute == null){
            return;
        }
        initComponents();
        this.jLabel_Title.setText(attribute.name);
        initList(attribute);
    }
    
    private void initList(Attribute attribute){
        jList.setModel(new DefaultListModel<>());
        list = Session.getCBR().getValues(attribute);
        
        DefaultListModel listModel = (DefaultListModel) jList.getModel();
        listModel.clear();
        for (String string : list) {
            listModel.addElement(string);            
        }
        jList.setModel(listModel);
        if(!listModel.isEmpty()){
            jList.setSelectedIndex(0);
        }
    }
    
    private void updateList(){
        DefaultListModel listModel = (DefaultListModel) jList.getModel();
        listModel.clear();
        for (String string : list) {
            if(string.toUpperCase().contains(jTextField.getText().toUpperCase())){
                listModel.addElement(string);
            }
        }
        jList.setModel(listModel);
        if(!listModel.isEmpty()){
            jList.setSelectedIndex(0);
        }
    }
    
    private void selectAttribute(java.awt.event.MouseEvent evt){
        if(evt.getClickCount() == 2){
            ok = true;
            this.dispose();
        }
    }
    
    private void keyTyped(java.awt.event.KeyEvent evt) {
        ok = false;
         switch (evt.getKeyCode()) {
             case KeyEvent.VK_ENTER:
                 ok = true;
                 dispose();
                 break;
             case KeyEvent.VK_UP:
                 if(jList.getSelectedIndex() > 0){
                    jList.setSelectedIndex(jList.getSelectedIndex() - 1);
                 }
                 break;
             case KeyEvent.VK_DOWN:
                 if(jList.getSelectedIndex() < jList.getModel().getSize()){
                    jList.setSelectedIndex(jList.getSelectedIndex() + 1);
                 }
                 break;
             default:
                 break;
         }
    }
    
    public String getValue(){
        if(ok){
            return jList.getSelectedValue();
        }
        return null;
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel_Search = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 300));
        setPreferredSize(new java.awt.Dimension(700, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(650, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(98, 126, 146));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setText("Attribute Text");
        jPanel2.add(jLabel_Title);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel12.setMinimumSize(new java.awt.Dimension(550, 300));
        jPanel12.setPreferredSize(new java.awt.Dimension(550, 300));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel_Search.setText("   Search:");
        jLabel_Search.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel14.add(jLabel_Search);

        jTextField.setMinimumSize(new java.awt.Dimension(400, 22));
        jTextField.setPreferredSize(new java.awt.Dimension(540, 22));
        jTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldCaretUpdate(evt);
            }
        });
        jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldKeyTyped(evt);
            }
        });
        jPanel14.add(jTextField);

        jPanel12.add(jPanel14);

        jScrollPane.setPreferredSize(new java.awt.Dimension(258, 275));

        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jListKeyTyped(evt);
            }
        });
        jScrollPane.setViewportView(jList);

        jPanel12.add(jScrollPane);

        jPanel1.add(jPanel12, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldCaretUpdate
        updateList();
    }//GEN-LAST:event_jTextFieldCaretUpdate

    private void jListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_jListKeyTyped

    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        selectAttribute(evt);
    }//GEN-LAST:event_jListMouseClicked

    private void jTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyTyped
        keyTyped(evt);
    }//GEN-LAST:event_jTextFieldKeyTyped

    private void jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeyPressed
        keyTyped(evt);
    }//GEN-LAST:event_jTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAttributes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                JAttributes dialog = new JAttributes(new javax.swing.JFrame(), true, Attribute.PORTASORIGEM);
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Search;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
