/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.jcolibri.utils.components;

import br.edu.jcolibri.constants.Attribute;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.ListModel;

/**
 *
 * @author Lori Machado Filho
 */
public class JAttributeListener extends javax.swing.JPanel {
    
    private Attribute attribute;
    private JFrame parent;
    /**
     * Creates new form JAttributeListener
     */
    public JAttributeListener() {
        initComponents();
    }
    
    public JAttributeListener(JFrame parent, Attribute attribute, ArrayList<String> attributes) {
        initComponents();
        this.jLabel.setText(attribute.name);       
        jList.setModel(new DefaultListModel<>());
        DefaultListModel listModel = (DefaultListModel) jList.getModel();
        listModel.clear();
        if(attributes != null){
            attributes.forEach((a) -> {
                listModel.addElement(a);
            });
            jList.setModel(listModel);
        }
        this.attribute = attribute;
        this.parent = parent;        
    }
    
    private void search(){
        JAttributes jAttributes = new JAttributes(parent, true, attribute);
        jAttributes.setVisible(true);
        jTextField.setText(jAttributes.getValue() != null ? jAttributes.getValue() :jTextField.getText());
        if(jTextField.getText().trim().isEmpty()){
            jButton_Search.requestFocus();
        } else {
            jButton_Add.requestFocus();
        }
    }
    
    public void setJTextFieldEditable(boolean editable) {
        jTextField.setEditable(editable);
    }
    
    public void setJTextFieldEnabled(boolean enabled) {
        jTextField.setEnabled(enabled);
    }
    
    public void setAllEnabled(boolean enabled) {        
        setAllEnabled(jPanel_Main, enabled);
    }
    
    private void setAllEnabled(Component component, boolean enabled) {        
        if (!(component instanceof JTabbedPane) && 
                !(component instanceof JTable)) {
            component.setEnabled(enabled);
        }
        
        if (component instanceof Container) {
            Container container = (Container) component;

            for (int i = 0; i < container.getComponentCount(); i++) {
                Component c = container.getComponent(i);
                if(!(c instanceof JLabel) || (c instanceof JLabel && component.getMouseListeners()!=null)){
                    setAllEnabled(c, enabled);
                }
            }
        }    
    }
 
   public ArrayList<String> getList() {
        ListModel model = jList.getModel();
        ArrayList<String> list = new ArrayList();
        for (int i = 0; i < model.getSize(); i++) {
            list.add((String) model.getElementAt(i));
        }
        return list;        
    }
   
  public Attribute getAttribute(){
      return this.attribute;
  }
  
  public void addList(ArrayList<String> useCasesRelationship){
        if (useCasesRelationship == null) {
            useCasesRelationship = new ArrayList<>();
        }
        jList.removeAll();
        DefaultListModel listModel = new DefaultListModel();
        for (String string : useCasesRelationship) {
            listModel.addElement(string);
        }
        jList.setModel(listModel);
  }
  
  public void addValue(String value){
      DefaultListModel dlm = (DefaultListModel) jList.getModel();
      dlm.addElement(value);
  }
  
  private void addValue(){
      if(jTextField.getText().trim().isEmpty()){
          return;
      }
      DefaultListModel dlm = (DefaultListModel) jList.getModel();
      for (int i = 0; i < dlm.size(); i++) {
          if(dlm.getElementAt(i).equals(jTextField.getText())){
              return;
          }
      }
      dlm.addElement(jTextField.getText());
      jTextField.setText(null);
      jButton_Search.requestFocus();
  }
  
  private void removeValue(){
        DefaultListModel dlm = (DefaultListModel) jList.getModel();
        dlm.remove(jList.getSelectedIndex());
  }
  
  public JList getJList(){
      return this.jList;
  }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextField = new javax.swing.JTextField();
        jButton_Add = new javax.swing.JButton();
        jButton_Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(254, 254, 254));
        setMinimumSize(new java.awt.Dimension(650, 125));
        setPreferredSize(new java.awt.Dimension(650, 125));
        setLayout(new java.awt.BorderLayout());

        jPanel_Main.setBackground(new java.awt.Color(254, 254, 254));
        jPanel_Main.setMinimumSize(new java.awt.Dimension(650, 125));
        jPanel_Main.setPreferredSize(new java.awt.Dimension(650, 125));
        jPanel_Main.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel15.setBackground(new java.awt.Color(254, 254, 254));
        jPanel15.setMinimumSize(new java.awt.Dimension(160, 100));
        jPanel15.setPreferredSize(new java.awt.Dimension(160, 100));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel.setBackground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Label:");
        jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel.setMaximumSize(new java.awt.Dimension(160, 16));
        jLabel.setMinimumSize(new java.awt.Dimension(160, 16));
        jLabel.setPreferredSize(new java.awt.Dimension(160, 16));
        jPanel1.add(jLabel);

        jPanel15.add(jPanel1);

        jPanel_Main.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(254, 254, 254));
        jPanel16.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel17.setBackground(new java.awt.Color(254, 254, 254));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jPanel9.setBackground(new java.awt.Color(254, 254, 254));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        jTextField.setMinimumSize(new java.awt.Dimension(400, 22));
        jTextField.setPreferredSize(new java.awt.Dimension(400, 22));
        jPanel9.add(jTextField);

        jPanel17.add(jPanel9);

        jButton_Add.setBackground(new java.awt.Color(35, 35, 35));
        jButton_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/jcolibri/img/plus.png"))); // NOI18N
        jButton_Add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_Add.setContentAreaFilled(false);
        jButton_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Add.setMaximumSize(new java.awt.Dimension(40, 25));
        jButton_Add.setMinimumSize(new java.awt.Dimension(40, 25));
        jButton_Add.setPreferredSize(new java.awt.Dimension(35, 20));
        jButton_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_AddMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_AddMouseEntered(evt);
            }
        });
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel17.add(jButton_Add);

        jButton_Search.setBackground(new java.awt.Color(254, 254, 254));
        jButton_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/jcolibri/img/search.png"))); // NOI18N
        jButton_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_Search.setContentAreaFilled(false);
        jButton_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Search.setMaximumSize(new java.awt.Dimension(40, 25));
        jButton_Search.setMinimumSize(new java.awt.Dimension(40, 25));
        jButton_Search.setPreferredSize(new java.awt.Dimension(35, 20));
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });
        jPanel17.add(jButton_Search);

        jPanel16.add(jPanel17);

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(258, 75));

        jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList.setSelectionBackground(new java.awt.Color(124, 167, 184));
        jList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jListKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        jPanel16.add(jScrollPane1);

        jPanel_Main.add(jPanel16);

        add(jPanel_Main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        addValue();
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        search();
    }//GEN-LAST:event_jButton_SearchActionPerformed

    private void jListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_DELETE){
            removeValue();
        }
    }//GEN-LAST:event_jListKeyTyped

    private void jButton_AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddMouseEntered
        jButton_Add.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButton_AddMouseEntered

    private void jButton_AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Search;
    private javax.swing.JLabel jLabel;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
